### ISSUE TITLE
Split the production commands into a separate justfile

### ISSUE THREAD

**Issue by madwort** [opensafely-core/backend-server#137]
as mentioned in this review https://github.com/opensafely-core/backend-server/pull/127#pullrequestreview-1571614176 

* [x] move tests out of `/justfile`
  * https://github.com/opensafely-core/backend-server/pull/123
* [ ] ...more stuff...?

**Comment by madwort** [comment]
@bloodearnest had an idea about copying the management justfile into ~jobrunner for the enduser to use

**Comment by bloodearnest** [comment]
So, for commands that are job-runner related, e.g. stop/restart/killjob/prepare_for_reboot, etc,
we could have these in a separate justfile. Part of installing jobrunner would be copying the justfile into the ~jobrunner directory.

Then, operators can use `just jobrunner-restart` or whatever w/o worrying about the backend-server commands, as they'll be complete separate.

**Comment by madwort** [comment]
I think we may have done enough on this now

**Comment by madwort** [comment]
@bloodearnest agrees  https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1694701320692259?thread_ts=1694700806.226039&cid=C03ELD5FEAU
