### ISSUE TITLE
Docker 24!

### ISSUE THREAD

**Issue by madwort** [opensafely-core/backend-server#168]
Backends are Ubuntu 20.04, this has had docker-20 for a long time. Ubuntu updates has just added docker-24.something, which we noticed for the first time on Monday.

Upgrading requires careful coordination to restart everything (jobs etc), maybe during a db maintenance window. Pause jobs on a Monday? 

Reasons to update: security?, up-to-date-ness, users are using more recent versions (auto-updating), we may be testing against docker-24 (CI builds on latest?), 

TODO: verify what CI is using

question: should we unsubscribe backends from ubuntu-updates?
question: is this a security issue?

**Comment by evansd** [comment]
After completing this upgrade we should confirm whether `unveil` is now supported from inside containers by running:
```
docker run --rm ghcr.io/opensafely-core/ehrql:v0 isolation-report
```
And seeing whether `read_env_vars` is described as `BLOCKED` inside `subprocess_run_isolated`.

If it is, we should enable `unveil` here:
https://github.com/opensafely-core/ehrql/blob/75a3bfdddf1fe715cd543e76fe088b23ca498819/ehrql/loaders.py#L120-L127

**Comment by bloodearnest** [comment]
Sad panda 

![Image](https://github.com/opensafely-core/backend-server/assets/1042/77765cfc-197e-4616-95b6-abd850f53c8a)

**Comment by evansd** [comment]
Well... this is actually very odd. The system still claims not to support `unveil`:
![image](https://github.com/opensafely-core/backend-server/assets/19630/cb347247-c0c4-44eb-b66d-1d019e20b58e)

And also, our current isolation configuration doesn't _attempt_ to block the env var read. So when I run it locally I get `ALLOWED`, even though `unveil` in Docker works fine on my machine.

So I think this is more weird news than good news; and possibly even bad news given that we don't quite know what's going on here!
