### ISSUE TITLE
Remove accounts for those users who've been removed from the developers list

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/backend-server#181]
We've recently removed a few people from the [developers](https://github.com/opensafely-core/backend-server/blob/main/developers) list as they no longer require that level of access to the secure environments. There are some manual steps required for this to take effect on on TPP and EMIS.

Specific users to verify removal:
- [ ] Will J Hulme
- [ ] Seb Bacon
- [ ] ...?

**Comment by madwort** [comment]
actions might include:

* disable account
* remove from sudo group
* remove SSH keys
* delete account
