### ISSUE TITLE
Update release hatch certificates on a timer

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/backend-server#184]
Currently, we use the nginx-served `backends.opensafely.org` vhost along with regular letsencrypt on dokku4 to get up-to-date certificates for `$BACKEND.backends.opensafely.org`. We re-use the same private key - just the certs are updated.

The backends can access this to grab updated certificates for release-hatch using:

```
cd release-hatch
openssl s_client -showcerts -connect backends.opensafely.org:443 </dev/null 2>/dev/null| sed -n '/^-----BEGIN CERT/,/^-----END CERT/p' > certs/fullchain.pem
docker-compose restart release-hatch
```

However, we could do with this being run regularly on a timer, probably as part of the default release-hatch timer.

**Comment by benbc** [comment]
@bloodearnest Can we specify that the time should be set up via version-controlled config management, not manually?

**Comment by bloodearnest** [comment]
That is the way we do it for everything on the backend-server repo?

**Comment by benbc** [comment]
It's not how we applied the seccomp fix for EMIS.

**Comment by bloodearnest** [comment]
Point taken.

There were some extenuating circumstances there, to be fair. Its a very different class of issue.
