### ISSUE TITLE
Configure `/etc/hosts` entries on backends

### ISSUE THREAD

**Issue by evansd** [opensafely-core/backend-server#206]
We have been having issues with flaky DNS inside the TPP backend. Specifically, failures from `git` with the error:
```
Could not resolve host: github-proxy.opensafely.org
```

Given that all the external services we talk to are hosted on a single, fixed IP (which must be fixed, for firewall configuration purposes) there's no point relying on external DNS for these and we should hardcode them in `/etc/hosts`.

Specifically, all of `{jobs,github-proxy,docker-proxy,collector}.opensafely.org` should point to `157.245.31.108`.

Note that the machine uses cloud-init, so it won't be sufficient to just update `/etc/hosts`.

To address the immediate issue, an entry for `github-proxy.opensafely.org` has been manually added to `/etc/hosts` and `/etc/cloud/templates/hosts.debian.tmpl`.

Related thread:
https://bennettoxford.slack.com/archives/C069YDR4NCA/p1708075680058539

**Comment by bloodearnest** [comment]
This has now been escalated as a result of https://github.com/opensafely-core/backend-server/issues/224

We're going to manually manged DNS for all domains we need, and disabling all resolver config. This will improve reliability and security.

Care needs taking that the hosts /etc/hosts values are used from within airlock docker container.
