### ISSUE TITLE
Clarify user addition

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/backend-server#238]
In README, and as comment in `developers`, call out that you should check the developer permissions log before adding new people.

Also, remove mention of researchers/reviewers groups from that section of the README, they are no longer used.

**Comment by CLStables** [comment]
FYI, this issue is on my list of things needed to complete the work around the Developer Permissions Log, so I've got a reminder to check on it every couple of weeks (and tick it off my list once it's done) :)

**Comment by CLStables** [comment]
Slackbot just reminded me to check on this ticket again - this is me checking...

**Comment by CLStables** [comment]
Thank you @rebkwok !!
