### ISSUE TITLE
Figure out ad-hoc level 4 file syncing in TPP

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/backend-server#71]
Now that we ahve the VM, the canonical source for level 4 files is `/srv/medium_privacy/workspaces` in the VM filesystem.

However, Bennett researcher staff still use the host windows machine to run ad hoc notebooks (using docker for windows) that generate output files, and these need sharing to level 4 for viewing and releasing.

Currently, I'm doing this via the tried and tested bash/rsync/tmux combo:

![image](https://user-images.githubusercontent.com/1042/172676659-096d7334-3a4b-44b6-9594-ae5fdd7cfb1a.png)

This copies files from the old E:\FILESFORLEVEL4 dir into the the new level 4 storage, where they are synced by TPPs sync script.

This sucks, because a) it needs manually re-running after a VM/tmux restart and b) it can result in copying over level 4 files if researchers are not careful with directories.

In the short term, we should probably:

a) make this a ~jobrunner cron job
b) copy it into a specific directory in level 4 storage.

longer term, hopefully databuilder curation/exploration work will render this manual process not necessary, and we can drop it.

**Comment by lucyb** [comment]
I'm closing this because we aren't currently using rsync and are moving away from using ad-hoc notebooks.
