### ISSUE TITLE
Add OTel metrics to backend-server

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/backend-server#83]
We need to export OTel cpu/memory/disk metrics from the server, both for the host and for each docker container.

Ideally we need to be able to apply tags to these metrics for: backend, job id (for job docker containers), workspace, project, user to help us link in with the traces for those jobs.

This may be blocked on paying for honeycomb

**Acceptance Criteria**
* Be able to view current metrics from within Honeycomb and compare it with historic data (i.e last week, last month, etc)
* Be able to overlay the metrics with job information in order to identify any patterns

**Comment by lucyb** [comment]
(Note: I added some acceptance criteria. Please edit if you feel it's appropriate)

**Comment by bloodearnest** [comment]
The collector has been deployed, and partially configured, but we need honeycomb pro before going further

**Comment by bloodearnest** [comment]
This is mostly done. 

There's a PR waiting to land, but the image and config in that PR is already deployed and working

https://github.com/opensafely-core/sysadmin/pull/79

Am moving this to blocked, as am just waiting on that PR, and that probably should be Tom W or Lucy, who are away this week.

**Comment by lucyb** [comment]
@bloodearnest Can this be closed now or is there more to do?
